name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Primes
        id: cache-primes
        uses: chinchaun/nativelink-cache@v0.0.1-beta
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes
        env:
          NATIVELINK_API_KEY: ${{ secrets.NATIVELINK_API_KEY }}
          NATIVELINK_REMOTE_CACHE_URL: ${{ secrets.NATIVELINK_REMOTE_CACHE_URL }}

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate-primes.sh -d prime-numbers

      - name: Use Prime Numbers
        run: /primes.sh -d prime-numbers
